version: '3.8'
services:
  diffrhythm:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      # args:
      #  TORCH_VERSION: cuda12 # TORCH_VERSION Options = cuda12, cuda128, cuda11, rocm, xpu, cpu
    image: diffrhythm
    container_name: diffrhythm
#    volumes:
#      - ./scripts:/app/scripts
#      - ./output:/app/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
